pipelines:
  custom:
    develop:
      - step:
          name: Install Node Module and Create React Build for WellnessAdmin Develop Branch
          image: node:14.17.1
          size: 2x
          script:
            - yarn install
            - export NODE_OPTIONS=--max_old_space_size=8192
            - CI=false yarn run build
          artifacts:
            - build/**
      - step:
          name: Deploy To S3 Bucket
          deployment: Development
          script:
            - pipe: atlassian/aws-s3-deploy:0.2.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $S3_BUCKET
                ACL: 'public-read'
                LOCAL_PATH: 'build'
      - step:
          name: Invalidate CloudFront Cache
          script:
            - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                DISTRIBUTION_ID: $DISTRIBUTION_ID
    production:
      - step:
          name: Install Node Module and Create React Build for WellnessAdmin Develop Branch
          image: node:14.17.1
          size: 2x
          script:
            - yarn install
            - export NODE_OPTIONS=--max_old_space_size=8192
            - CI=false yarn run build
          artifacts:
            - build/**
      - step:
          name: Deploy To S3 Bucket
          deployment: Production
          script:
            - pipe: atlassian/aws-s3-deploy:0.2.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $S3_BUCKET
                ACL: 'public-read'
                LOCAL_PATH: 'build'
      - step:
          name: Invalidate CloudFront Cache
          script:
            - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                DISTRIBUTION_ID: $DISTRIBUTION_ID_PROD
