const actions = {
  SET_DOCTOR_NAME: 'DOCTOR/SET_NAME',
  SET_DOCTOR_RECORD_ID: 'DOCTOR/SET_DOCTOR_RECORD_ID',
  SET_DOCTOR_INFO: 'DOCTOR/SET_DOCTOR_INFO',
  SET_SELECTED_DOCTOR_LIST: 'DOCTOR/SET_SELECTED_DOCTOR_LIST',
}

export default actions
